### ISSUE TITLE
[Bug]: Card not working after 2025.05 update

### ISSUE THREAD

**Issue by IgorSimic** [EnkodoNL/tabbed-card-programmable#10]
### Description

No tab labels, just icons, not clicable.
I love this card and I need it in my config.
It looks like original tabbed card is already fixed.

![Image](https://github.com/user-attachments/assets/abeacaab-9fcf-4a90-9a1e-3e1853ba91be)
![Image](https://github.com/user-attachments/assets/7f3ecdac-6093-4ede-908d-b1a6613432de)

### Environment

```Markdown
- Browser: All
- Home Assistant Version: 2025.05    
- Tabbed Card Version: 0.3.4
```

### Reproducible configuration

```YAML
- type: custom:tabbed-card-programmable
  tabs:
    - card:
        type: button
        entity: light.bed_light
        tap_action:
          action: toggle
        show_name: true
        show_icon: true
        show_state: true
      attributes:
        label: Button
    - card:
        type: entities
        title: Air Quality
        entities:
          - air_quality.demo_air_quality_home
          - air_quality.demo_air_quality_office
      attributes:
        label: Air Quality
    - card:
        type: entities
        title: Binary sensor
        entities:
          - binary_sensor.basement_floor_wet
          - binary_sensor.movement_backyard
      attributes:
        label: Binary Sensor
    - card:
        type: entities
        title: Calendar
        entities:
          - entity: calendar.calendar_1
            name: "1"
          - entity: calendar.calendar_2
            name: "2"
      attributes:
        label: Calendar
```
